services:
  nginx:
    extends:
      file: base.yml
      service: nginx
    links:
      - app
    ports:
      - "5001:5001"

  postgres:
    extends:
      file: base.yml
      service: postgres

  app:
    extends:
      file: base.yml
      service: app
    environment:
      - DJANGO_SETTINGS_MODULE=service.settings.dev_settings
    command: sh ./scripts/dev.sh
    build:
      args:
        - DJANGO_ENV=dev
    links:
      - postgres
    ports:
      - "8001:8001"
