# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='aboutinfo',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.CharField(max_length=128, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.CharField(max_length=128, verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='event',
            field=models.CharField(max_length=128, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project',
            field=models.CharField(max_length=128, verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='researchline',
            name='research_line',
            field=models.CharField(max_length=128, verbose_name='research line'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='service',
            field=models.CharField(max_length=128, verbose_name='service'),
        ),
    ]
