# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0002_auto_20180119_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'ordering': ('id',), 'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.RemoveField(
            model_name='aboutinfo',
            name='image',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='', verbose_name='project image'),
        ),
    ]
