# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0004_gallery_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutInfo',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='url',
            new_name='url_repository',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='url_project',
            field=models.URLField(blank=True, null=True, verbose_name='project info url'),
        ),
        migrations.AddField(
            model_name='researchline',
            name='url_research',
            field=models.URLField(default='No Name', verbose_name='research line url'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='course'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='homeinfo',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='researchline',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='service',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='service'),
        ),
    ]
