# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-05 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0005_auto_20180326_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='type_course',
            field=models.PositiveSmallIntegerField(choices=[(200, 'Course'), (210, 'Event')], default=200, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='url_course',
            field=models.URLField(default='No Name', verbose_name='course url'),
        ),
        migrations.AddField(
            model_name='repository',
            name='type_repository',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Material'), (110, 'Software'), (120, 'Repository')], default=100, verbose_name='type of repository'),
        ),
    ]
