# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0006_auto_20180505_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchline',
            name='type_line',
            field=models.PositiveSmallIntegerField(choices=[(300, 'Current Projects'), (310, 'Past Projects')], default=100, verbose_name='type of research line'),
        ),
    ]
