# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0007_researchline_type_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='type_project',
            field=models.PositiveSmallIntegerField(choices=[(400, 'Current Project'), (410, 'Past Project')], default=400, verbose_name='type of project'),
        ),
        migrations.AlterField(
            model_name='researchline',
            name='type_line',
            field=models.PositiveSmallIntegerField(choices=[(300, 'Current Lines'), (310, 'Past Lines')], default=300, verbose_name='type of research line'),
        ),
    ]
