# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0008_auto_20180510_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='static', verbose_name='video'),
        ),
    ]
