# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0009_homeinfo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='video'),
        ),
    ]
