# Generated by Django 2.1 on 2025-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0010_auto_20180806_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='type_course',
            field=models.PositiveSmallIntegerField(choices=[(200, 'Course'), (210, 'Event'), (220, 'Conference')], default=200, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='type_repository',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Academic Material'), (110, 'Software'), (120, 'Repository'), (130, 'Documents'), (140, 'Other Resources')], default=100, verbose_name='type of repository'),
        ),
    ]
