# Generated by Django 2.1 on 2025-08-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0011_auto_20250211_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.TextField(max_length=70, verbose_name='Reference')),
                ('status', models.PositiveSmallIntegerField(choices=[(500, 'OPEN'), (510, 'CLOSED')], verbose_name='Status')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Publication Date')),
                ('deadline_date', models.DateTimeField(auto_now_add=True, verbose_name='Deadline Date')),
                ('type', models.PositiveSmallIntegerField(choices=[(600, 'HALF'), (610, 'FULL')], verbose_name='Type of Scholarship')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('duration', models.TextField(max_length=200, verbose_name='Duration')),
                ('duties', models.TextField(max_length=3000, verbose_name='Duties')),
                ('application', models.TextField(max_length=3000, verbose_name='Application')),
                ('starting_date', models.DateTimeField(auto_now_add=True, verbose_name='Starting Date')),
                ('country', models.TextField(max_length=100, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Scholarship',
                'verbose_name_plural': 'Scholarships',
                'ordering': ('id',),
            },
        ),
    ]
