# Generated by Django 2.1 on 2025-08-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupinformation', '0012_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='deadline_date',
            field=models.DateTimeField(verbose_name='Deadline Date'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='publication_date',
            field=models.DateTimeField(verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='starting_date',
            field=models.DateTimeField(verbose_name='Starting Date'),
        ),
    ]
