REPOSITORY_CHOICES_MT = 100
REPOSITORY_CHOICES_SF = 110
REPOSITORY_CHOICES_RP = 120
REPOSITORY_CHOICES_DO = 130
REPOSITORY_CHOICES_OR = 140

REPOSITORY_CHOICES = (
    (REPOSITORY_CHOICES_MT, 'Academic Material'),
    (REPOSITORY_CHOICES_SF, 'Software'),
    (REPOSITORY_CHOICES_RP, 'Repository'),
    (REPOSITORY_CHOICES_DO, 'Documents'),
    (REPOSITORY_CHOICES_OR, 'Other Resources'),
)


COURSE_CHOICES_CO = 200
COURSE_CHOICES_EV = 210
COURSE_CHOICES_CN = 220

COURSE_CHOICES = (
    (COURSE_CHOICES_CO, 'Course'),
    (COURSE_CHOICES_EV, 'Event'),
    (COURSE_CHOICES_CN, 'Conference'),
)


LINE_CHOICES_CU = 300
LINE_CHOICES_PA = 310

LINE_CHOICES = (
    (LINE_CHOICES_CU, 'Current Lines'),
    (LINE_CHOICES_PA, 'Past Lines'),
)


PROJECT_CHOICES_CU = 400
PROJECT_CHOICES_PA = 410

PROJECT_CHOICES = (
    (PROJECT_CHOICES_CU, 'Current Project'),
    (PROJECT_CHOICES_PA, 'Past Project'),
)

SCHOLARSHIP_CHOICES_OP = 500
SCHOLARSHIP_CHOICES_CL = 510

SCHOLARSHIP_CHOICES = (
    (SCHOLARSHIP_CHOICES_OP, 'OPEN'),
    (SCHOLARSHIP_CHOICES_CL, 'CLOSED'),
)

SCHOLARSHIP_TYPES_HA = 600
SCHOLARSHIP_TYPES_FU = 610

SCHOLARSHIP_TYPES = (
    (SCHOLARSHIP_TYPES_HA, 'HALF'),
    (SCHOLARSHIP_TYPES_FU, 'FULL'),
)
