# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 15:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(error_messages={'min_length': 'The field "full name" must have at least %(limit_value)d characters (it has %(show_value)d).'}, max_length=128, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('photo', models.ImageField(max_length=256, upload_to='', verbose_name='photo')),
                ('mobile_phone', models.CharField(blank=True, default='', error_messages={'min_length': 'Field "Mobile Phone" must have at least %(limit_value)d digits (it has %(show_value)d).'}, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9 ,]*$', message='Number entered is not valid. Only numbers areallowed. If there is more than one, they have to be separsted by coma (,).'), django.core.validators.MinLengthValidator(10)], verbose_name='mobile phone')),
                ('website', models.URLField(verbose_name='website')),
                ('description', models.TextField(verbose_name='description')),
                ('type_member', models.PositiveSmallIntegerField(choices=[(100, 'Principal Researchers'), (110, 'Associate Researchers'), (120, 'External Researchers'), (130, 'PhD Students'), (140, 'Master Students'), (150, 'Volunteers')], verbose_name='type of member')),
                ('research_interest', models.TextField(verbose_name='research interest')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='name of publication')),
                ('event_of_publication', models.CharField(max_length=200, verbose_name='event of publication')),
                ('author', models.TextField(default='No Name', verbose_name='coauthors')),
                ('abstract', models.TextField(verbose_name='abstract')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year of publication')),
                ('member', models.ForeignKey(default='No Name', on_delete=django.db.models.deletion.CASCADE, to='members.Member', verbose_name='author')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ('id',),
            },
        ),
    ]
