# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='mobile_phone',
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='website'),
        ),
    ]
