# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180119_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='url_publication',
            field=models.URLField(blank=True, null=True, verbose_name='url of publication'),
        ),
    ]
