# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_publication_url_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
