# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20180326_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='url_publication',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='url of publication'),
        ),
    ]
