# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180328_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='active',
            field=models.PositiveSmallIntegerField(choices=[(200, 'Si'), (210, 'No')], default=200, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(max_length=256, upload_to='uploads', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type_member',
            field=models.PositiveSmallIntegerField(choices=[(100, 'Principal Researchers'), (110, 'Associate Researchers'), (120, 'External Researchers'), (130, 'PhD Students'), (140, 'Master Students'), (150, 'Junior'), (160, 'Administrative Assistant'), (170, 'Web Master'), (180, 'Volunteer'), (190, 'Head of the Group')], verbose_name='type of member'),
        ),
    ]
