# Generated by Django 2.1 on 2018-12-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180815_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.PositiveSmallIntegerField(choices=[(200, 'Yes'), (210, 'No')], default=200, verbose_name='active'),
        ),
    ]
