# Generated by Django 2.1 on 2021-02-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20181214_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='member',
            name='type_member',
            field=models.PositiveSmallIntegerField(choices=[(40, 'Senior Researchers'), (50, 'Postdoctoral Researchers'), (80, 'Honorary Researchers'), (100, 'Principal Researchers'), (110, 'Associate Researchers'), (120, 'Collaborator Researchers'), (130, 'PhD Students'), (140, 'Master Students'), (150, 'Junior'), (160, 'Administrative Assistant'), (170, 'Web Master'), (180, 'Volunteer'), (190, 'Head of the Group'), (90, 'Degree Students'), (70, 'Former Members'), (60, 'Editor & Translator')], verbose_name='type of member'),
        ),
    ]
