# Generated by Django 2.1 on 2025-02-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20210214_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='type_member',
            field=models.PositiveSmallIntegerField(choices=[(20, 'Research Engineer'), (40, 'Senior Researchers'), (50, 'Postdoctoral Researchers'), (80, 'Honorary Research Fellows'), (100, 'Research Associates'), (120, 'Collaborator Researchers'), (130, 'Research Assistants - Level III'), (140, 'Research Assistants - Level II'), (150, 'Junior Researchers'), (160, 'Administrative Assistant'), (170, 'Web Master'), (180, 'Volunteer'), (190, 'Head of the Group'), (90, 'Research Assistants - Level I'), (70, 'Former Members'), (60, 'Analyst')], verbose_name='type of member'),
        ),
    ]
