# Generated by Django 2.1 on 2025-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20250503_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='type_member_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'None'), (20, 'Head of the Group'), (30, 'Analyst'), (40, 'Project Controls Manager'), (50, 'Principal Researcher'), (60, 'Senior Researcher'), (70, 'Junior Researcher'), (80, 'Research Assistant - Level III'), (90, 'Research Assistant - Level II'), (100, 'Research Assistant - Level I'), (110, 'Research Engineer'), (120, 'Research Volunteer'), (130, 'Honorary Research Fellow'), (140, 'External Collaborator'), (150, 'Web Master')], null=True, verbose_name='type of member'),
        ),
        migrations.AddField(
            model_name='member',
            name='type_member_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'None'), (20, 'Head of the Group'), (30, 'Analyst'), (40, 'Project Controls Manager'), (50, 'Principal Researcher'), (60, 'Senior Researcher'), (70, 'Junior Researcher'), (80, 'Research Assistant - Level III'), (90, 'Research Assistant - Level II'), (100, 'Research Assistant - Level I'), (110, 'Research Engineer'), (120, 'Research Volunteer'), (130, 'Honorary Research Fellow'), (140, 'External Collaborator'), (150, 'Web Master')], null=True, verbose_name='type of member'),
        ),
    ]
