# Generated by Django 2.1 on 2025-05-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20250505_1710'),
        ('members', '0010_auto_20250211_0201'),
    ]

    operations = [
    ]
