# Generated by Django 2.1 on 2025-05-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20250505_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='publications_url',
            field=models.CharField(blank=True, max_length=250, verbose_name='URL of publications'),
        ),
    ]
