# Generated by Django 2.1 on 2025-05-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_merge_20250506_1456'),
        ('members', '0013_member_publications_url'),
    ]

    operations = [
    ]
